.TH "casino.JeuCasino" 3 "Sun Jan 12 2020" "Projet : Hotel "Blue Bay Caracao"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
casino.JeuCasino \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBMise\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJeuCasino\fP (\fBClient\fP client)"
.br
.ti -1c
.RI "void \fBInsertionMonnaie\fP (boolean utiliseLaCagnotte, double monnaieInseree)"
.br
.ti -1c
.RI "void \fBFaitesVosJeux\fP (ArrayList< Double > monnaieMise, ArrayList< String > mise)"
.br
.ti -1c
.RI "void \fBtirageNumero\fP ()"
.br
.ti -1c
.RI "void \fBgestionGain\fP ()"
.br
.ti -1c
.RI "void \fBVersementGain\fP ()"
.br
.ti -1c
.RI "void \fBderoulementJeuComplet\fP (boolean utiliseCagnotte, double monnaieInseree, ArrayList< Double > monnaieMise, ArrayList< String > mise)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet : Hotel 'Blue Bay Caracao' from the source code\&.
