.TH "casino.JeuCasino.Mise" 3 "Sun Jan 12 2020" "Projet : Hotel "Blue Bay Caracao"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
casino.JeuCasino.Mise \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPAIR\fP"
.br
.ti -1c
.RI "\fBIMPAIR\fP"
.br
.ti -1c
.RI "\fBROUGE\fP"
.br
.ti -1c
.RI "\fBNOIR\fP"
.br
.ti -1c
.RI "\fBMANQUE\fP"
.br
.ti -1c
.RI "\fBPASSE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet : Hotel 'Blue Bay Caracao' from the source code\&.
