.TH "client.Client" 3 "Sun Jan 12 2020" "Projet : Hotel "Blue Bay Caracao"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client.Client \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (String prénom, String nom, String naissance, String email, String téléphone)"
.br
.ti -1c
.RI "String \fBgetPrénom\fP ()"
.br
.ti -1c
.RI "void \fBsetPrénom\fP (String newPrénom)"
.br
.ti -1c
.RI "String \fBgetNom\fP ()"
.br
.ti -1c
.RI "void \fBsetNom\fP (String newNom)"
.br
.ti -1c
.RI "String \fBgetNaissance\fP ()"
.br
.ti -1c
.RI "void \fBsetNaissance\fP (String naissance)"
.br
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.ti -1c
.RI "void \fBsetEmail\fP (String email)"
.br
.ti -1c
.RI "String \fBgetTéléphone\fP ()"
.br
.ti -1c
.RI "boolean \fBestUnEntier\fP (String téléphone)"
.br
.ti -1c
.RI "void \fBsetTéléphone\fP (String téléphone)"
.br
.ti -1c
.RI "double \fBgetCagnotte\fP ()"
.br
.ti -1c
.RI "void \fBsetCagnotte\fP (double newCagnotte)"
.br
.ti -1c
.RI "int \fBgetTicket\fP ()"
.br
.ti -1c
.RI "void \fBsetTicket\fP (int newTicket)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet : Hotel 'Blue Bay Caracao' from the source code\&.
