.TH "restaurant.Restaurant" 3 "Sun Jan 12 2020" "Projet : Hotel "Blue Bay Caracao"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
restaurant.Restaurant \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRestaurant\fP (ArrayList< \fBClient\fP > tableauClient)"
.br
.ti -1c
.RI "boolean \fBConvertitOuiEnBool\fP (String ouinon)"
.br
.ti -1c
.RI "void \fBcommande\fP ()"
.br
.ti -1c
.RI "void \fBCalculTotalPrix\fP ()"
.br
.ti -1c
.RI "void \fBReglement\fP ()"
.br
.ti -1c
.RI "void \fBDeroulementRestaurant\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ArrayList< \fBClient\fP > \fBtableauClient\fP = new ArrayList<\fBClient\fP>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauMojito\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauDaiquiri\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauPlat\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauAccompagnement\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauDessert\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "ArrayList< Boolean > \fBtableauBoisson\fP = new ArrayList<Boolean>()"
.br
.ti -1c
.RI "double \fBprixTotal\fP"
.br
.ti -1c
.RI "int \fBticketTotalMis\fP"
.br
.ti -1c
.RI "double \fBargentRestantAPayer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet : Hotel 'Blue Bay Caracao' from the source code\&.
