.TH "TestCasino" 3 "Sun Jan 12 2020" "Projet : Hotel "Blue Bay Caracao"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCasino \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[]args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet : Hotel 'Blue Bay Caracao' from the source code\&.
